name: caffeinate
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  order_tracker_zen: ^1.0.0+4
  flutter_local_notifications: ^17.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
  assets:
  - assets/images/
flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/images/logo.png
  min_sdk_android: 21
