// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMzD7yXmLIrGkFf-rL90ciRuCkkj9Iuj0',
    appId: '1:1031715005726:web:8d31902d9cf5d9474e550f',
    messagingSenderId: '1031715005726',
    projectId: 'caffeinate-9826b',
    authDomain: 'caffeinate-9826b.firebaseapp.com',
    storageBucket: 'caffeinate-9826b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZttdJsG9D7aO91k94SlCbXaM7SkUewLE',
    appId: '1:1031715005726:android:ad728ea9722c9e8a4e550f',
    messagingSenderId: '1031715005726',
    projectId: 'caffeinate-9826b',
    storageBucket: 'caffeinate-9826b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkbgCgSIQwbCh4tl0y_EJI7kj3Du81HUU',
    appId: '1:1031715005726:ios:f8e520acf9f0b8f84e550f',
    messagingSenderId: '1031715005726',
    projectId: 'caffeinate-9826b',
    storageBucket: 'caffeinate-9826b.appspot.com',
    iosBundleId: 'com.example.caffeinate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkbgCgSIQwbCh4tl0y_EJI7kj3Du81HUU',
    appId: '1:1031715005726:ios:2a3f31b382d95b9e4e550f',
    messagingSenderId: '1031715005726',
    projectId: 'caffeinate-9826b',
    storageBucket: 'caffeinate-9826b.appspot.com',
    iosBundleId: 'com.example.caffeinate.RunnerTests',
  );
}
